# Generated by Django 5.2.4 on 2025-07-24 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("columns", models.IntegerField(default=4)),
                ("benches_per_column", models.IntegerField(default=6)),
                ("students_per_bench", models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_id", models.CharField(max_length=20, unique=True)),
                ("batch", models.CharField(default="General", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Bench",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_num", models.IntegerField()),
                ("col_num", models.IntegerField()),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benches",
                        to="attendance.room",
                    ),
                ),
            ],
            options={
                "ordering": ["col_num", "row_num"],
            },
        ),
        migrations.CreateModel(
            name="SeatingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignment_time", models.DateTimeField(auto_now_add=True)),
                (
                    "bench",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.bench",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.student",
                    ),
                ),
            ],
            options={
                "ordering": ["assignment_time"],
            },
        ),
        migrations.AddField(
            model_name="bench",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                through="attendance.SeatingAssignment",
                to="attendance.student",
            ),
        ),
        migrations.CreateModel(
            name="Absentee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.room",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="attendance.student",
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="bench",
            unique_together={("room", "row_num", "col_num")},
        ),
    ]
